name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Git checkout this
      uses: actions/checkout@v2

    - name: Pull container images and prepare composition
      run: |
        sudo chown runner:docker /var/run/docker.sock
        # see https://github.com/nektos/act/issues/724#issuecomment-855390956

        echo "> docker compose pull"
        docker-compose pull
        echo "> docker image ls"
        docker image ls

        echo "> pwd"
        pwd
        echo "ls -lha"
        ls -lha

        echo "-- generate certs and keys --"
        cd keys
        bash generate_root_ca.sh
        bash generate_derived_certs.sh
        bash copy.sh ../secrets

    - name: Bring up container composition
      run: |
        docker-compose -p mongod-on-smb-container-composition up -d --no-build  # will pull missing images with build command in compose file

        sleep 10

        echo "> docker container ls --all"
        docker container ls --all

        echo "> docker volume ls"
        docker volume ls

        echo "-- docker images --"
        docker-compose images

        echo "-- mongodb log --"
        docker-compose logs mongodb

        echo "-- mongodb-backup log --"
        docker-compose logs mongodb-backup

        sleep 10 # run more tests

        # TODO: needs test for smb share availability, mongodb availability, backup procedures
        docker-compose down
